/* Objeto com os paths para os icones e background, hexadecimal das cores de texto, rgb das cores de fundo e array com as fraquezas de cada tipo  */

const types = {
  All: {
    icon: "types/icon-all.png",
    color: "#000000",
  },
  bug: {
    icon: "types/bug.png",
    modalBg: "modalBg/bug_bg.png",
    color: "#9BBA48",
    bgColor: "rgba(155, 186, 72, 0.1)",
    weakness: ["fire", "flying", "rock"],
  },
  dark: {
    icon: "types/dark.png",
    modalBg: "modalBg/dark_bg.png",
    color: "#595761",
    bgColor: "rgba(89, 87, 97, 0.1)",
    weakness: ["bug", "fairy", "fighting"],
  },
  dragon: {
    icon: "types/dragon.png",
    modalBg: "modalBg/dragon_bg.png",
    color: "#2C6AC1",
    bgColor: "rgba(44, 106, 193, 0.1)",
    weakness: ["dragon", "fairy", "ice"],
  },
  electric: {
    icon: "types/electric.png",
    modalBg: "modalBg/electric_bg.png",
    color: "#D4BC34",
    bgColor: "rgba(212, 188, 52, 0.1)",
    weakness: ["ground"],
  },
  fairy: {
    icon: "types/fairy.png",
    modalBg: "modalBg/fairy_bg.png",
    color: "#E296E1",
    bgColor: "rgba(226, 150, 225, 0.1)",
    weakness: ["poison", "steel"],
  },
  fighting: {
    icon: "types/fighting.png",
    modalBg: "modalBg/fighting_bg.png",
    color: "#C44D61",
    bgColor: "rgba(196, 77, 97, 0.1)",
    weakness: ["fairy", "flying", "psychic"],
  },
  ground: {
    icon: "types/ground.png",
    modalBg: "modalBg/ground_bg.png",
    color: "#CE8056",
    bgColor: "rgba(206, 128, 86, 0.1)",
    weakness: ["grass", "ice", "water"],
  },
  ice: {
    icon: "types/ice.png",
    modalBg: "modalBg/ice_bg.png",
    color: "#71BAAC",
    bgColor: "rgba(113, 186, 172, 0.1)",
    weakness: ["fighting", "fire", "rock", "steel"],
  },
  normal: {
    icon: "types/normal.png",
    modalBg: "modalBg/normal_bg.png",
    color: "#909090",
    bgColor: "rgba(144, 144, 144, 0.1)",
    weakness: ["fighting"],
  },
  poison: {
    icon: "types/poison.png",
    modalBg: "modalBg/poison_bg.png",
    color: "#AC6ACA",
    bgColor: "rgba(172, 106, 202, 0.1)",
    weakness: ["ground", "psychic"],
  },
  psychic: {
    icon: "types/psychic.png",
    modalBg: "modalBg/psychic_bg.png",
    color: "#EB8B85",
    bgColor: "rgba(235, 139, 133, 0.1)",
    weakness: ["bug", "dark", "ghost"],
  },
  rock: {
    icon: "types/rock.png",
    modalBg: "modalBg/rock_bg.png",
    color: "#84BEB3",
    bgColor: "rgba(132, 190, 179, 0.1)",
    weakness: ["fighting", "grass", "ground", "steel", "water"],
  },
  ghost: {
    icon: "types/ghost.png",
    modalBg: "modalBg/ghost_bg.png",
    color: "#616EB7",
    bgColor: "rgba(97, 110, 183, 0.1)",
    weakness: ["dark", "ghost"],
  },
  grass: {
    icon: "types/grass.png",
    modalBg: "modalBg/grass_bg.png",
    color: "#73B861",
    bgColor: "rgba(115, 184, 97, 0.1)",
    weakness: ["bug", "fire", "flying", "ice", "poison"],
  },
  steel: {
    icon: "types/steel.png",
    modalBg: "modalBg/steel_bg.png",
    color: "#6594A1",
    bgColor: "rgba(101, 148, 161, 0.1)",
    weakness: ["fighting", "fire", "ground"],
  },
  water: {
    icon: "types/water.png",
    modalBg: "modalBg/water_bg.png",
    color: "#4F77BE",
    bgColor: "rgba(79, 119, 190, 0.1)",
    weakness: ["electric", "grass"],
  },
  fire: {
    icon: "types/fire.png",
    modalBg: "modalBg/fire_bg.png",
    color: "#E96303",
    bgColor: "rgba(233, 99, 3, 0.1)",
    weakness: ["ground", "rock", "water"],
  },
  flying: {
    icon: "types/flying.png",
    modalBg: "modalBg/flying_bg.png",
    color: "#758CBD",
    bgColor: "rgba(117, 139, 189, 0.1)",
    weakness: ["electric", "ice", "rock"],
  },
};

export default types;
